services:
  api:
    build: .
    container_name: llm-chat-api
    env_file:
      - .env
    environment:
      APP_ENV: ${APP_ENV:-development}
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
    ports:
      - "8001:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - llmnet

  postgres:
    image: postgres:16-alpine
    container_name: llm-chat-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-llmchat}
      POSTGRES_USER: ${POSTGRES_USER:-llmchat}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-llmchatpass}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
        interval: 5s
        timeout: 5s
        retries: 5
    networks:
      - llmnet

  redis:
    image: redis:7-alpine
    container_name: llm-chat-redis
    ports:
     - "6380:6379"
    networks:
      - llmnet

networks:
  llmnet:

volumes:
  postgres_data:

